package cats.syntax

trait AllSyntax
    extends AnySyntax
    with ApplySyntax
    with BifunctorSyntax
    with CoflatMapSyntax
    with ComonadSyntax
    with ComposeSyntax
    with ContravariantSyntax
    with EqSyntax
    with FlatMapSyntax
    with FoldableSyntax
    with FunctorSyntax
    with InvariantSyntax
    with MonadCombineSyntax
    with MonadFilterSyntax
    with OrderSyntax
    with OptionSyntax
    with PartialOrderSyntax
    with ProfunctorSyntax
    with SemigroupSyntax
    with SemigroupKSyntax
    with ShowSyntax
    with SplitSyntax
    with StrongSyntax
